baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10
enableRobotsTXT = true
relativeurls = true
canonifyURLs = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Well, it worked on MY machine"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = 2026
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"https://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/tmswfrk\">James Clarke</a>"
    ]

[params.author]
    name = "nilpointer.blog"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "A Blog for the Uninitialized"
    copyright = '<a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank" rel="noopener">Licensed under Apache 2.0</a>'

  [languages.en.params]
    subtitle  = "Well, it worked on MY machine"

    [languages.en.params.logo]
      logoText = "curl -X POST /dev/null"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  # and submenus
  [[menu.main]]
    identifier  = "about"
    name        = "About Me"
    url         = "/about"
    hasChildren = true

[[params.social]]
    name = "email"
    url  = "mailto:tmswfrk@gmail.com"

[[params.social]]
    name = "github"
    url  = "https://github.com/tmswfrk"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/jmclarke10"